### ISSUE TITLE
Aggregate::handle

### ISSUE THREAD

**Issue by seanpianka** [serverlesstechnology/cqrs#11]
Hello 👋 , thanks for creating this crate, this is a great improvement on domain_patterns!

I'm trying to learn about the library, but am a bit confused on an aspect of the design. Could you please explain why aggregates handle their own commands in this framework? And, how can infrastructure or domain services be used within an impl of this `handle` method without also tying the instantiation of an aggregate instance to those services? (particularly to avoid mocking those services to test the domain objects). 

In my experience, aggregates are concerned only with the business logic, whereas it is an "application service" that (a separate type/service) that `handle`s commands against a particular aggregate. In order to do that, this application service queries repositories, shares references to domain services (e.g. for a domain object to use when performing a business operation), persists new events created by business operations (and invoke event handlers in non-ES systems), etc.

Any help you could provide to clarify would be appreciated, thanks 🙂

**Comment by serverlesstechnology** [comment]
My apologies for the late response, our Github seems to have been neglected recently, sadly we've also been a bit late in updating our public repositories the latest code that we've been using in-house and documentation.

= - (

There is now a short explanation of using external services in our [User Guide](https://doc.rust-cqrs.org/application_service_injection.html). Generally, these services should be injected with your command ensuring
- compiler protection
- simplified mocking for tests


We've experimented with automated injection of services a la [Tower](https://crates.io/crates/tower) but to date we've found those experiments to violate our 'lightweight' target for this library.
