### ISSUE TITLE
Events lost on error?

### ISSUE THREAD

**Issue by duaneking** [serverlesstechnology/cqrs#12]
Looking deeply at the code in the CQRS execute_with_metadata call, it looks like the 'aggregate.handle(command)' call can never return errors that can be recovered because of the use of '?', Since we are not given a way to recover.

Is this intentional? Was the intention to put a hard barrier up and not allow the processing of errors? I'm under the impression that in rust it's generally considered an anti-pattern to use this '?' flow because you're not able to correctly deal with errors due to the forced panic. Is my understanding wrong?

This seems like an error to me, because I would want to be able to handle a recoverable error in a clean way as part of this pipeline,or at least log it cleanly to a dead letter queue or something, but the create doesn't allow me to even add a logger to the failure, since it will panic as soon as the result is returned.

**Comment by serverlesstechnology** [comment]
Hi Duane,

The use of the question mark operator '?' just acts to propagate the error to a higher level. When you handle any error from the framework you can use the '?' to further propagate it up your stack if you have an error that implements `From<AggregateError>`, but you can always handle it with a `match` statement. 

Hope that answers your question.
