### ISSUE TITLE
Is this crate no longer maintained?

### ISSUE THREAD

**Issue by duaneking** [serverlesstechnology/cqrs#13]
I noticed that there is a CQRS-ES2 crate that is forked from this project; that project has made big updates about ownership and makes large changes, so should this project be considered unmaintained and should we instead be using that other crate?

I guess what I'm really asking here is if the CQRS-ES2 crate should be considered the modern replacement of this one that we should actually use instead?

I'm seeking guidance on the right CQRS crate to use for a new project.

**Comment by serverlesstechnology** [comment]
Hi Duane,

I think you reached us via email so this is probably a redundant reply. It is very much maintained and under development, please see our [user documentation](https://doc.rust-cqrs.org/intro.html) and [demo application](https://github.com/serverlesstechnology/cqrs-demo) for more help.

**Comment by CumpsD** [comment]
Any chance to see these 2 ever come together again? Seems like a lot of things can be shared: https://github.com/cqrs-es2/cqrs-es2/blob/master/ChangeLog.md

**Comment by duaneking** [comment]
It honestly feels like a merge should happen.  There are a number of issues in both, and if they were merged that would provide the opportunities for the weaknesses in both to be fixed.
