### ISSUE TITLE
Support for multiple event tables?

### ISSUE THREAD

**Issue by bennichols** [serverlesstechnology/cqrs#16]
Hi, thanks for all your work. I'm learning a lot about how crqs/es works using your module and applying it against a real world modelling scenario. I saw in your book that you say:

> A single table can be used for all aggregate events and this is usually the ideal setup for development and testing. For production systems it is recommended that each aggregate have a table solely dedicated to its' events.

I looked through the code, but it appears that this isn't supported at this point unless I'm missing something. I didn't see anything else in the upcoming 0.3 commit log either, but I may have missed something. Is this in development or on the roadmap? Cheers!

**Comment by davegarred** [comment]
Hello @bennichols, we've run into the same issue here! 

Event table names will be configurable in v0.3 which should be out later this month. Note that this will be a rather large change as we bring together a number of changes from several internal forks.

Thanks for the interest!

**Comment by serverlesstechnology** [comment]
We have published v0.3.0 which now allows configuration of table names. Thanks again for the interest and submitting this!
