### ISSUE TITLE
Open source the user guide

### ISSUE THREAD

**Issue by CumpsD** [serverlesstechnology/cqrs#22]
I want to submit a PR for doc.rust-cqrs.org, but where is the repo to submit the PR to?

**Comment by serverlesstechnology** [comment]
Hi @CumpsD,

It appears that I have neglected to open source this (it currently resides amongst a group of internal planning documents). I'll bump that up on the TODO list. Thank you for the help!

**Comment by CumpsD** [comment]
Thanks. I've followed the guide, but a lot of things had to be changed to make it work.

For example:
It specified cqrs-es 0.3.0 in getting started, while 0.4.0 is out https://doc.rust-cqrs.org/intro_getting_started.html

When you pin to 0.3.0 and try to do the Aggregate: https://doc.rust-cqrs.org/intro_add_aggregate.html
It complains about Services not being known, since that got added to 0.4.0

But if you pin to 0.4.0 the `handle` syntax needs to be the following or it complains about lifetimes:

```
    async fn handle(&self, command: Self::Command, services: &Self::Services) -> Result<Vec<Self::Event>, Self::Error> {
```

In https://doc.rust-cqrs.org/demo_application_framework.html we do a WriteCheck event, but in the pages before we never implemented it. We implemented a Withdraw. So the output you print doesn't match what happens when you follow the guide.

With 0.4.0 the syntax of https://doc.rust-cqrs.org/test_add_more.html and https://doc.rust-cqrs.org/test_add_first.html has to change to `AccountTestFramework::with(BankAccountServices)` and `BankAccountError` needs to derive `PartialEq` for:

```
    fn test_withdraw_money_funds_not_available() {
        let expected = BankAccountError("funds not available".to_string());

        AccountTestFramework::with(BankAccountServices)
            .given_no_previous_events()
            .when(BankAccountCommand::WithdrawMoney { amount: 200.0 })
            .then_expect_error(expected);
    }
```

**Comment by serverlesstechnology** [comment]
Thanks again for pointing out this oversight @CumpsD. Book source is now located in `docs/book/src`.
