### ISSUE TITLE
About event replay and read model changes

### ISSUE THREAD

**Issue by jonaslimads** [serverlesstechnology/cqrs#23]
A view payload `{"name": "John"}` is compatible with the view
```rust
struct ProductView {
    name: String,
}
```

But it will be incompatible if we change this read model to 
```rust
struct ProductView {
    name: String,
    price: u32
}
```

It will then result in `DeserializationError(Error("missing field `events`", line: 0, column: 0)`. Is it safe to assume that we should add a deserialization fallback in case it fails or even an explicit "view upcast" (I don't even know if this is technically correct) in the same fashion as the event upcast?

Incompatible payloads will exist from the moment the new read model is deployed until the events are replayed to rebuild the views, which can take some time to be fully replayed and updated.

About event replay, I see that there is only `PersistedEventRepository::get_events` (by single aggregate_id) and `ViewRepository::update_view` (for single view). I forked the repos to add (it's still WIP):

```rust
// PersistedEventRepository
   async fn get_multiple_aggregate_events<A: Aggregate>(
        &self,
        aggregate_ids: Vec<&str>,
    ) -> Result<HashMap<String, Vec<SerializedEvent>>, PersistenceError>;
    
// ViewRepository
    async fn update_views(&self, views: Vec<(V, ViewContext)>) -> Result<(), PersistenceError>;
```

So we can batch select and update aggregate and views. What are your thoughts?

**Comment by serverlesstechnology** [comment]
Hi @jonaslimads, 

To handle legacy events in your database you should [use an `EventUpcaster`](https://docs.rs/cqrs-es/0.4.2/cqrs_es/persist/trait.EventUpcaster.html) to transform them to the correct value before deserialization.

You are correct that the tools for a full event replay are not yet available. I expect one or more of these to be added to this library within the coming months.

**Comment by serverlesstechnology** [comment]
[QueryReplay struct](https://docs.rs/cqrs-es/0.4.3/cqrs_es/persist/struct.QueryReplay.html) added in v0.4.3
