### ISSUE TITLE
How to compose a single view from multiple aggregates where an aggregate references another aggregate?

### ISSUE THREAD

**Issue by jonaslimads** [serverlesstechnology/cqrs#24]
Hi,

Given a single view composed by two aggregates roots, Vendor and Product:

```rust
pub struct VendorView {
    pub id: String,
    pub name: String,
    pub products: Vec<VendorViewProduct>,
}

pub struct VendorViewProduct {
    pub id: String,
    pub name: String,
    pub price: u32,
}
```

where `id` is the aggregate ID of each aggregate root, and **the actual view_id is** `VendorView.id` copied from the Vendor. This view stores all products of a single vendor. The Product aggregate has a `vendor_id` field to reference the Vendor.

I also wondered whether Product should not be a aggregate root at all, but in many scenarios/commands the Product itself is the root to be referenced, with its own stock, prices and so on. So it seems for this case the model is easier if Vendor and Products are separate aggregates.

To dispatch events to this view from separate CQRS instances of each aggregate we implement both `View<Vendor>` and `View<Product>` for VendorView. However we have no way to pass this `vendor_id` as `view_id` down to the Query because:

```rust
pub trait Query<A: Aggregate>: Send + Sync {
    async fn dispatch(&self, aggregate_id: &str, events: &[EventEnvelope<A>]);
}

// cqrs.rs
impl<A, ES> CqrsFramework<A, ES> {
    pub async fn execute_with_metadata(...) -> Result<(), AggregateError<A::Error>> {
let aggregate_context = self.store.load_aggregate(aggregate_id).await?;
        // here the aggregate_id is the Product's. Ok
        let aggregate_context = self.store.load_aggregate(aggregate_id).await?;
        // .....
        for processor in &self.queries {
            let dispatch_events = committed_events.as_slice();
            // for most queries, specially the ones exclusive to the Product, this is OK
            // but for VendorView this is not ok since Project.id != VendorView.id
            processor.dispatch(aggregate_id, dispatch_events).await;
        }
    }
}
```

One workaround I ended up doing was:

```rust
pub trait Query<A: Aggregate>: Send + Sync {
    async fn dispatch(&self, aggregate_id: &str, events: &[EventEnvelope<A>], secondary_id: Option<&str>);
}

pub trait Aggregate: Default + Serialize + DeserializeOwned + Sync + Send {
    fn secondary_id(&self) -> Option<String> {
        None
    }
}

impl Aggregate for Product {
    fn secondary_id(&self) -> Option<String> {
        Some(self.vendor_id.clone())
    }
}

impl<A, ES> CqrsFramework<A, ES> {
    pub async fn execute_with_metadata(...) -> Result<(), AggregateError<A::Error>> {
        // ..... I had to load_aggregate again to get the aggregate with the newly applied event
        let aggregate_context = self.store.load_aggregate(aggregate_id).await?;
        let aggregate = aggregate_context.aggregate();
        let secondary_id = aggregate.secondary_id();
       
        for processor in &self.queries {
            let dispatch_events = committed_events.as_slice();
            processor
                .dispatch(aggregate_id, dispatch_events, secondary_id.as_deref())
                .await;
        }
    }
}
```

Thanks!

**Comment by serverlesstechnology** [comment]
This is an issue using `GenericQuery` since the aggregate id is expected to be the view id. This quickly compounds in a production system when more than two aggregates affect the same materialized view (a not uncommon situation).

The correct way to do this is via custom queries for each aggregate. In the future this will be solved with the use of secondary indices on the views underneath `GenericQuery`, but for now these must be hand rolled. 

You can model these queries based on `GenericQuery` but instead load the desired view(s) via the appropriate parameter on the event.

**Comment by jonaslimads** [comment]
I'm not using `GenericQuery` though, I'm implementing `View` and `Query` traits for both aggregates.

> instead load the desired view(s) via the appropriate parameter on the event

Given that `Query::dispatch` only has parameters `aggregate_id` and `EventEnvelope`, we can:

1. Have `vendor_id` in all Product's events only to satisfy that specific view. Not a good solution
2. Inject `vendor_id` into the metadata. It would be even better if we could inject this after the events are committed, so we don't actually store a metadata with `vendor_id` into the database, since the `vendor_id` is already present in the first event.

I'll try this metadata approach

**Comment by serverlesstechnology** [comment]
Ah, I think I see the issue. You should wait until you process the individual event to load up the correct view rather than attempting to loading the view before (as `GenericQuery` does).

```
pub trait Query<A: Aggregate>: Send + Sync {
    async fn dispatch(&self, _aggregate_id: &str, events: &[EventEnvelope<A>]) {
        for event in events {
            let mut view = self.view_database.load_view(event.payload.some_id);
            view.modify_something(...);
            self.view_database.save_view(view);
        }
    }
}
```

Sometimes you'll need to translate one parameter to your view id via an additional view (i.e., database table) to find the id that you're looking for. This could be something like a database table with two fields that links each product to the correct vendor.

```
pub trait Query<A: Aggregate>: Send + Sync {
    async fn dispatch(&self, _aggregate_id: &str, events: &[EventEnvelope<A>]) {
        for event in events {
            let view_id = self.view_database.lookup_view_id(event.payload.some_other_id);
            let mut view = self.view_database.load_view(view_id);
            view.modify_something(...);
            self.view_database.save_view(view);
        }
    }
}
```

**Comment by jonaslimads** [comment]
I got it now, so the lookup solves, in fact the lookup is quite handy in many other scenarios. Thanks!
