### ISSUE TITLE
move the demo application into this repo

### ISSUE THREAD

**Issue by danieleades** [serverlesstechnology/cqrs#43]
the demo application should probably be moved into this repo, and this repo modified to be a cargo workspace

this ensures that this library and the demo application are updated in lockstep.

I had a quick go at this, but ran into some subtle version issues. I suspect `postgres-es` would also need to be added to the workspace to prevent multiple different versions of `cqrs` being pulled into the dependency tree

**Comment by davegarred** [comment]
Thanks for the input @danieleades. I would like to avoid pulling any of the persistence modules into this project to keep things clean, particularly for users that may use a custom persistence mechanism or to avoid issues adding new databases.

I've considered combining the persistence modules (using feature flags to select the desired database) but on initial tries at this I've run into conflicts (particularly with later versions of the MySql driver) and thus opted to keep things separated for now.

It would certainly be nice to have less crates to manage though so we should think about this in the future as things stabilize (though with the speed that Rust moves I'm not sure when or if that will happen).

**Comment by danieleades** [comment]
sure thing. To be clear, i'm not proposing adding the repos to this crate, but to store them in this repo as separate crates in a Cargo workspace

**Comment by danieleades** [comment]
I think this is worth revisiting

>I've considered combining the persistence modules (using feature flags to select the desired database) but on initial tries at this I've run into conflicts (particularly with later versions of the MySql driver) and thus opted to keep things separated for now.

this problem is *worse* when the persistence module is stored in an entirely separate repo, not better. They will only become more incompatible over time

**Comment by davegarred** [comment]
It is a valid concern and I think you've pulled me over to your side of it. The current strategy seems unnecessarily complex to maintain.
Let's plan to wind down those projects and move that work over here.
