### ISSUE TITLE
Feature: Make aggregate id, aggregate type, event type, event version types parametric

### ISSUE THREAD

**Issue by epsilonhalbe** [serverlesstechnology/cqrs#51]
I had a look at the serialization into postgres via postgres-es and the current implementation of
```
aggregate_id: string
aggregate_type: string
event_type: string
event_version string
```
is quite limiting.

Speaking from experience in a production db 5 years in with a hundred billion events using queries on the event store get super slow, bc. `text` is not a good base type, keeping those types more parametric so one can choose something more performant like `uuid` for ids, postgres enums for event/aggregate type (which will add some error potential to the process of adding new events/aggregate, for the sake of performance).

and the event version as it currently is used is a bit problematic - the examples suggest using a version kinda string "x.y.z", but I believe string has a lexicographic ordering - so wouldn't "0.20.0" be before "0.3.0"?

**Comment by davegarred** [comment]
@epsilonhalbe in postgres there is no performance penalty for using `text`. Nonetheless, I agree that adding configurability would be beneficial and I have examined that in the past. The tl;dr is that while supporting 3 database systems (with more planned) this would be difficult to maintain.

For specialized systems you should consider using one of the persistence packages as a start and implementing [a custom EventStore](https://docs.rs/cqrs-es/latest/cqrs_es/trait.EventStore.html).

Note that the events are never ordered based on the event_version, this is used solely for event upcasting (where `0.20.0` > `0.3.0`).

**Comment by epsilonhalbe** [comment]
I get the point that supporting 3 databases is already tough, I think the polymorphism could help, but I don't know enough about rust how to encode that polymorphic IDs etc. will be serializable to all of the DBs.

I don't understand how you don't need an ordering for upcasting, but I think I need to have a more in-depth look at the tutorial/code/demo.

And as far as I know querying a postgres event store with event-type `text` can be quite slow.

**Comment by davegarred** [comment]
Ordering is handled via [the sequence](https://github.com/serverlesstechnology/cqrs/blob/master/src/event.rs#L68). Every event can [be uniquely identified](https://github.com/serverlesstechnology/cqrs/blob/master/src/persist/serialized_event.rs#L12-L17) by the combination of: 
- Event type
- Aggregate ID
- Sequence

**Comment by epsilonhalbe** [comment]
thank for the clarification
