### ISSUE TITLE
How to check for aggregate existence?

### ISSUE THREAD

**Issue by sancho20021** [serverlesstechnology/cqrs#52]
If I understand correctly, implementations of Store are intended to return Default::default() in case the aggregate is not found.
Sometimes in handling commands (say, extending someones fitness club card, where card is an aggregate) you have to check for the entity existence.

**Workaround**: make the aggregate an enum with two variants to simulate `Option`.

The case where this is needed seems very common, so I would suggest to modify the framework to satisfy these needs. 
But I have almost no experience in ES/CQRS, so I may be missing something.

**Comment by davegarred** [comment]
Hi @sancho20021, for any feedback you'll want to use a query, this is a very simple one to configure. The most basic setup would be to use a [`GenericQuery`](https://docs.rs/cqrs-es/latest/cqrs_es/persist/struct.GenericQuery.html) to serialize a view with this list.

```
struct ExistingAggregatesView {
  aggregate_ids: Vec<String>
}

impl View<MyAggregate> for ExistingAggregatesView {
    fn update(&mut self, event: &EventEnvelope<MyAggregate>) {
        self.aggregate_ids.push(event.aggregate_id);
    }
}
```

This obviously only works with small number of aggregates. For a production system you'd probably want to use a database table with a single `aggregate_id` column and create a custom query.

```
struct ExistingAggregatesQuery {
    database_client: DatabaseClient,
}
#[async_trait]
impl Query<MyAggregate> for ExistingAggregatesQuery {
    async fn dispatch(&self, aggregate_id: &str, events: &[EventEnvelope<MyAggregate>]) {
        for event in events {
            self.database_client.execute("INSERT INTO aggregate_id_table VALUES (?)", event.aggregate_id);
        }
    }
}
```

**Comment by sancho20021** [comment]
Thank you. Will I be able to access these queries /views inside the `handle` of a `command`?

**Comment by davegarred** [comment]
Accessing the view from within the aggregate is accomplished in a similar fashion by configuring [your aggregate's `Services`](https://docs.rs/cqrs-es/0.4.5/cqrs_es/trait.Aggregate.html#associatedtype.Services) associated type.

For the latter example this might look like:
```
struct MyServices {
  db_client: Box<dyn AbstractDatabaseClient>,
}
```
Note the database client should be a boxed dynamic type since you'll need to swap it out with a mock client in your tests.

This client is then available within the `handle` method of your aggregate.

Take a look at [our services example](https://github.com/serverlesstechnology/cqrs-demo/blob/master/src/services.rs) in the demo application for a complete example ([client test implementation is here](https://github.com/serverlesstechnology/cqrs-demo/blob/master/src/domain/aggregate.rs#L295-L298)).

**Comment by sancho20021** [comment]
> Hi @sancho20021, for any feedback you'll want to use a query, this is a very simple one to configure. The most basic setup would be to use a [`GenericQuery`](https://docs.rs/cqrs-es/latest/cqrs_es/persist/struct.GenericQuery.html) to serialize a view with this list.
> 
> ```
> struct ExistingAggregatesView {
>   aggregate_ids: Vec<String>
> }
> 
> impl View<MyAggregate> for ExistingAggregatesView {
>     fn update(&mut self, event: &EventEnvelope<MyAggregate>) {
>         self.aggregate_ids.push(event.aggregate_id);
>     }
> }
> ```

Okay, but how can I create a Query which will use this View in memory, without any `ViewRepository`?

https://doc.rust-cqrs.org/application_persisted_views.html in the tutorial they wrap similar view in a PostgresViewRepository, but I would like to have an in-memory query which I would use in handling requests of my server.

**Comment by davegarred** [comment]
> 
> Okay, but how can I create a Query which will use this View in memory, without any `ViewRepository`?
> 
> https://doc.rust-cqrs.org/application_persisted_views.html in the tutorial they wrap similar view in a PostgresViewRepository, but I would like to have an in-memory query which I would use in handling requests for my server.

See [the `SimpleLoggingQuery` example](https://github.com/serverlesstechnology/cqrs-demo/blob/master/src/queries.rs#L10-L22) in our demo application. Something similar can be used to accept new events and persist information in memory.
