### ISSUE TITLE
Adding Queries and Views after events were emitted.

### ISSUE THREAD

**Issue by andoriyu** [serverlesstechnology/cqrs#64]
`Query` only works within a single instance, unless persisted somewhere. `GenericQuery` is only working correctly if it was created before the first event.

There is `QueryReplay` but that replay is all or nothing. That means adding a new query after bunch of events were emitted is needlessly hard:

 - Persisted query could be messed up if the event log was replayed, but there are some events between replay and plugin query into `CqrsFramework`.
   - If not using `GenericQuery`, in my case I'm dumping everything into a table and query that table from other places, so I will need to truncate the table before replying.
 - If I want to avoid persisting `Query`, then I'm left with manually replaying the entire log every time I intend to read it
 - Deciding to replay or not is also confusing – how do you tell whether the view was materialized or not? 

Moreover: say I have 2 instances that use PostgreSQL as backing for events and views. If host-1 dies before it dispatched all events to queries, and host-2 emits some events – then the view will be incorrect since the persistent view never got updated from host-1.

Unless I'm missing something, I think [`PersistedEventRepository`](https://docs.rs/cqrs-es/latest/cqrs_es/persist/trait.PersistedEventRepository.html#) should have methods to stream events since some arbitrary sequence. Essentially [`PersistedEventRepository::get_last_events`](https://docs.rs/cqrs-es/latest/cqrs_es/persist/trait.PersistedEventRepository.html#tymethod.get_last_events), but without `aggregate_id`.

This would allow having non-persistent queries that can lazily updated.

**Comment by davegarred** [comment]
> `Query` only works within a single instance, unless persisted somewhere. `GenericQuery` is only working correctly if it was created before the first event.

After a new `GenericQuery` is added you should run a `QueryReplay` to populate it with previous aggregate instances, after which it will operate normally.

> There is `QueryReplay` but that replay is all or nothing. That means adding a new query after bunch of events were emitted is needlessly hard:

For simple queries this should be a straightforward process (though a large query replay can certainly take significant time). For more complex queries or very large tables it's likely some custom solutions will be needed depending on your requirements. I've found this to be fairly common in real world deployments.
 
> Moreover: say I have 2 instances that use PostgreSQL as backing for events and views. If host-1 dies before it dispatched all events to queries, and host-2 emits some events – then the view will be incorrect since the persistent view never got updated from host-1.

You're correct that this could be an issue, and if you're using a `GenericQuery` it would require manual intervention. As above, a custom solution would be the right answer.

I've considered a more robust persisted query (e.g., adding secondary indices, parallelization, fault-tolerance), but my experience has been that real-world requirements vary widely and trying to meet all the possibilities in one implementation is unlikely to be successful. Also, one of this projects tenets is to [keep this library lightweight](https://github.com/serverlesstechnology/cqrs/blob/main/docs/tenets.md#be-lightweight---prefer-distributed-over-monolithic-solutions).

For those reasons, in a complex production system you should implement your own query that meets all of your requirements, using `GenericQuery` only for the pattern it provides.

> Unless I'm missing something, I think [`PersistedEventRepository`](https://docs.rs/cqrs-es/latest/cqrs_es/persist/trait.PersistedEventRepository.html#) should have methods to stream events since some arbitrary sequence. Essentially [`PersistedEventRepository::get_last_events`](https://docs.rs/cqrs-es/latest/cqrs_es/persist/trait.PersistedEventRepository.html#tymethod.get_last_events), but without `aggregate_id`.

Are you looking for [the  `stream_all_events` method](https://docs.rs/cqrs-es/latest/cqrs_es/persist/trait.PersistedEventRepository.html#tymethod.stream_all_events)?

**Comment by davegarred** [comment]
> No, specifically a method to get/stream all events starting at some point, not all events from the beginning.

_"At some point"_ is difficult to do. If you're using a single command server you could use a time field but that could have issues if you're sharding the work. Here a custom solution based on the requirements of the system (and likely the database platform in use) are going to be needed for correctly replaying events.

**Comment by andoriyu** [comment]
> > No, specifically a method to get/stream all events starting at some point, not all events from the beginning.
> 
> _"At some point"_ is difficult to do. If you're using a single command server you could use a time field but that could have issues if you're sharding the work. Here a custom solution based on the requirements of the system (and likely the database platform in use) are going to be needed for correctly replaying events.

@davegarred ahh I see. Yeah I didn't think about that.

In our version, we're using [`ULID`](https://github.com/ulid/spec) for all IDs. I think as long as events for each aggregate remain ordered, it's not a big deal if two aggregates have events emitted within the same millisecond, and they get ordered "wrong".

I believe EventStoreDB does something similar, but it has a global sequence counter, similar to sequence in PostgreSQL and `AUTOINCREMENT` in SQLite.
