### ISSUE TITLE
CQRS no ES

### ISSUE THREAD

**Issue by Tomperez98** [serverlesstechnology/cqrs#67]
Is there a way to use this crate to as an `AggregateSource` CQRS Framework without the event sourcing?

I don't need the event history but only the aggregate current state persisted in my database.

**Comment by davegarred** [comment]
Hi @Tomperez98,

Sounds like you're looking for an aggregate store. This will use the persisted aggregate as the source of truth (events will still be stored).
https://docs.rs/cqrs-es/latest/cqrs_es/persist/struct.PersistedEventStore.html#method.new_aggregate_store

Each of the persistence libraries has helper methods to assist in this, postgres-es for example:
https://docs.rs/postgres-es/0.4.9/postgres_es/fn.postgres_aggregate_cqrs.html

**Comment by Tomperez98** [comment]
Thanks! I'll try to write a Python library inspired by this create. Really useful framework
