### ISSUE TITLE
Implement Nats Jetstream based store

### ISSUE THREAD

**Issue by andrewwebber** [serverlesstechnology/cqrs#92]
I was wondering if anyone would be interesting in exploring a [Nats Jetstream](https://docs.nats.io/nats-concepts/jetstream) based persistence layer.

I have put together an implementation [here](https://github.com/andrewwebber/nats-es) which I am currently experimenting on in production.

Persist trait implementations for Nats- https://github.com/andrewwebber/nats-es

**Comment by davegarred** [comment]
We have no plans for supporting NATS in these libraries, but if you build out a well-tested, full implementation please let us know so we can link to it.
