### ISSUE TITLE
Documentation and Demo mismatch

### ISSUE THREAD

**Issue by lambdalisue** [serverlesstechnology/cqrs#99]
There were many parts in the documentation that lacked information such as 'which file to write in' or a complete implementation of each section, so I was reading it while referring to the demo simultaneously. However, upon reaching the chapter on application implementation, I noticed that many parts differed between the documentation and the demo, which has caused me to stop progressing. The current documentation seems outdated—would it be better to just learn from the demo alone?

**Comment by davegarred** [comment]
Hi @lambdalisue , it's quite possible that they've diverged at some point. Can you point to any specific places?

Note that the documentation can be found [here](https://github.com/serverlesstechnology/cqrs/tree/main/docs/book/src).

**Comment by lambdalisue** [comment]
Thanks for clarifying. I'll follow the demo for now.

After the "Building an application" section, the differences between the documentation and demo became more noticeable. Are there any plans to update the documentation to align with the demo, or could PRs be submitted?

**Comment by davegarred** [comment]
Yes, PRs are ideal where you find these.
